### ISSUE TITLE
Failure of web tooling benchmark on 4.X

### ISSUE THREAD

**Issue by mhdawson** [nodejs/benchmarking#201]
Seems to be a persistent failure for the last few days.

Wondering if something changed in the benchmark to make it incompatible with 4.X since it is still running ok on 6.x and 8.x.

https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-4.x/803/console

```
{};'" --self > build/uglify-js-bundled.js


> web-tooling-benchmark@0.3.2 build /home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark
> webpack

/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/src/cli-flags-helper.js:35
      return [...targetList];
              ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/webpack.config.js:9:20)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at requireConfig (/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/bin/convert-argv.js:97:18)
    at /home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/bin/convert-argv.js:102:15)
    at /home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/bin/webpack.js:171:41
    at Object.Yargs.self.parse (/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:409:26)

npm ERR! Linux 3.13.0-133-generic
npm ERR! argv "/home/iojs/build/workspace/benchmark-footprint-4.x/node/out/Release/node" "/home/iojs/build/workspace/benchmark-footprint-4.x/node/out/Release/npm" "run" "build"
npm ERR! node v4.8.8-pre
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! web-tooling-benchmark@0.3.2 build: `webpack`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-tooling-benchmark@0.3.2 build script 'webpack'.
npm ERR! This is most likely a problem with the web-tooling-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs web-tooling-benchmark
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls web-tooling-benchmark
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/npm-debug.log

npm ERR! Linux 3.13.0-133-generic
npm ERR! argv "/home/iojs/build/workspace/benchmark-footprint-4.x/node/out/Release/node" "/home/iojs/build/workspace/benchmark-footprint-4.x/node/out/Release/npm" "install"
npm ERR! node v4.8.8-pre
npm ERR! npm  v2.15.11
npm ERR! code ELIFECYCLE
npm ERR! web-tooling-benchmark@0.3.2 postinstall: `npm run build:uglify-es-bundled && npm run build:uglify-js-bundled && npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the web-tooling-benchmark@0.3.2 postinstall script 'npm run build:uglify-es-bundled && npm run build:uglify-js-bundled && npm run build'.
npm ERR! This is most likely a problem with the web-tooling-benchmark package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build:uglify-es-bundled && npm run build:uglify-js-bundled && npm run build
```

**Comment by mhdawson** [comment]
@bmeurer can you take a look.

**Comment by mathiasbynens** [comment]
Array spread is not supported in Node.js v4. :( http://node.green/#ES2015-syntax-spread-------operator-with-arrays--in-function-calls A simple fix would be to use `Array.from()`. I’ll submit a patch.

**Comment by mathiasbynens** [comment]
The last “working” build was https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-4.x/800/console. On closer inspection of the log, it looks like a similar error is happening elsewhere:

```
+ tee web_tooling_benchmark.log
/home/iojs/build/workspace/benchmark-footprint-4.x/bench/web-tooling-benchmark/dist/cli.js:43288
            parserState.tokenComments[tokenHash].push(...token.comments);
                                                      ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
```

This use of the spread operator originates from coffeescript.

I suspect WTB never worked on Node.js v4.

**Comment by mathiasbynens** [comment]
Per https://github.com/v8/web-tooling-benchmark#building the Web Tooling Benchmark has not been tested on Node.js v4. I’ll go ahead and make it more clear that Node.js v4 is not supported. The fact that CI runs such as https://ci.nodejs.org/view/Node.js%20benchmark/job/benchmark-footprint-4.x/800/console have been passing seems like a bug.

**Comment by mhdawson** [comment]
@bmeurer can you confirm that we should just remove the web tooling benchmark from the v4.x runs ?

**Comment by bmeurer** [comment]
@mhdawson Yes.

**Comment by mhdawson** [comment]
Removed from job for 4.x and I see it is not in the graphs so closing.
